-- ============================================================
-- Employee Directory — sample data
-- Run after schema.sql (the Compiler's "Reset data" button runs
-- both automatically). 6 departments, 26 employees, 3-tier org.
-- ============================================================

INSERT INTO departments (name, description, color_hex) VALUES
    ('Engineering', 'Builds and ships the product.',                 '#1CB0F6'),
    ('Design',      'Shapes how the product looks, feels, and flows.', '#CE82FF'),
    ('Marketing',   'Tells the world what we''re building.',         '#FF9600'),
    ('Sales',       'Turns interest into customers.',                '#FFC800'),
    ('People Ops',  'Hires, supports, and grows the team.',          '#FF86D0'),
    ('Finance',     'Keeps the lights on and the numbers honest.',   '#1CC0C0');

-- Leadership first, so later rows can reference them via manager_id.
INSERT INTO employees (first_name, last_name, email, job_title, department_id, manager_id, salary, hire_date, employment_status, avatar_seed) VALUES
    ('Sam', 'Okafor', 'sam.okafor@orbitly.io', 'Chief Executive Officer',
        (SELECT department_id FROM departments WHERE name = 'Engineering'), NULL,
        210000, '2018-01-15', 'active', 'sam.okafor@orbitly.io');

INSERT INTO employees (first_name, last_name, email, job_title, department_id, manager_id, salary, hire_date, employment_status, avatar_seed) VALUES
    ('Priya', 'Nair', 'priya.nair@orbitly.io', 'VP of Engineering',
        (SELECT department_id FROM departments WHERE name = 'Engineering'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        175000, '2018-06-01', 'active', 'priya.nair@orbitly.io'),
    ('Elena', 'Petrova', 'elena.petrova@orbitly.io', 'Head of Design',
        (SELECT department_id FROM departments WHERE name = 'Design'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        158000, '2019-01-10', 'active', 'elena.petrova@orbitly.io'),
    ('Grace', 'Adeyemi', 'grace.adeyemi@orbitly.io', 'VP of Marketing',
        (SELECT department_id FROM departments WHERE name = 'Marketing'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        152000, '2019-08-05', 'active', 'grace.adeyemi@orbitly.io'),
    ('Isabella', 'Rossi', 'isabella.rossi@orbitly.io', 'VP of Sales',
        (SELECT department_id FROM departments WHERE name = 'Sales'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        160000, '2018-11-20', 'active', 'isabella.rossi@orbitly.io'),
    ('Olivia', 'Martins', 'olivia.martins@orbitly.io', 'Head of People',
        (SELECT department_id FROM departments WHERE name = 'People Ops'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        140000, '2019-04-02', 'active', 'olivia.martins@orbitly.io'),
    ('Benjamin', 'Cohen', 'benjamin.cohen@orbitly.io', 'Chief Financial Officer',
        (SELECT department_id FROM departments WHERE name = 'Finance'),
        (SELECT employee_id FROM employees WHERE email = 'sam.okafor@orbitly.io'),
        175000, '2018-09-17', 'active', 'benjamin.cohen@orbitly.io');

INSERT INTO employees (first_name, last_name, email, job_title, department_id, manager_id, salary, hire_date, employment_status, avatar_seed) VALUES
    ('Diego', 'Fernandez', 'diego.fernandez@orbitly.io', 'Senior Backend Engineer',
        (SELECT department_id FROM departments WHERE name = 'Engineering'),
        (SELECT employee_id FROM employees WHERE email = 'priya.nair@orbitly.io'),
        145000, '2019-03-11', 'active', 'diego.fernandez@orbitly.io'),
    ('Wei', 'Zhang', 'wei.zhang@orbitly.io', 'Frontend Engineer',
        (SELECT department_id FROM departments WHERE name = 'Engineering'),
        (SELECT employee_id FROM employees WHERE email = 'priya.nair@orbitly.io'),
        118000, '2021-02-08', 'active', 'wei.zhang@orbitly.io'),
    ('Fatima', 'Al-Sayed', 'fatima.alsayed@orbitly.io', 'DevOps Engineer',
        (SELECT department_id FROM departments WHERE name = 'Engineering'),
        (SELECT employee_id FROM employees WHERE email = 'priya.nair@orbitly.io'),
        132000, '2020-09-21', 'remote', 'fatima.alsayed@orbitly.io'),
    ('Noah', 'Kim', 'noah.kim@orbitly.io', 'Junior Engineer',
        (SELECT department_id FROM departments WHERE name = 'Engineering'),
        (SELECT employee_id FROM employees WHERE email = 'priya.nair@orbitly.io'),
        92000, '2023-07-03', 'active', 'noah.kim@orbitly.io'),
    ('Marcus', 'Webb', 'marcus.webb@orbitly.io', 'Senior Product Designer',
        (SELECT department_id FROM departments WHERE name = 'Design'),
        (SELECT employee_id FROM employees WHERE email = 'elena.petrova@orbitly.io'),
        128000, '2020-05-18', 'active', 'marcus.webb@orbitly.io'),
    ('Aiko', 'Tanaka', 'aiko.tanaka@orbitly.io', 'UX Researcher',
        (SELECT department_id FROM departments WHERE name = 'Design'),
        (SELECT employee_id FROM employees WHERE email = 'elena.petrova@orbitly.io'),
        104000, '2022-01-24', 'active', 'aiko.tanaka@orbitly.io'),
    ('Leo', 'Novak', 'leo.novak@orbitly.io', 'Visual Designer',
        (SELECT department_id FROM departments WHERE name = 'Design'),
        (SELECT employee_id FROM employees WHERE email = 'elena.petrova@orbitly.io'),
        95000, '2023-02-14', 'on_leave', 'leo.novak@orbitly.io'),
    ('Tomas', 'Rieger', 'tomas.rieger@orbitly.io', 'Content Strategist',
        (SELECT department_id FROM departments WHERE name = 'Marketing'),
        (SELECT employee_id FROM employees WHERE email = 'grace.adeyemi@orbitly.io'),
        98000, '2021-11-01', 'active', 'tomas.rieger@orbitly.io'),
    ('Hana', 'Suzuki', 'hana.suzuki@orbitly.io', 'Growth Marketer',
        (SELECT department_id FROM departments WHERE name = 'Marketing'),
        (SELECT employee_id FROM employees WHERE email = 'grace.adeyemi@orbitly.io'),
        101000, '2022-04-19', 'active', 'hana.suzuki@orbitly.io'),
    ('Owen', 'Brady', 'owen.brady@orbitly.io', 'Social Media Manager',
        (SELECT department_id FROM departments WHERE name = 'Marketing'),
        (SELECT employee_id FROM employees WHERE email = 'grace.adeyemi@orbitly.io'),
        86000, '2023-09-01', 'active', 'owen.brady@orbitly.io'),
    ('Karan', 'Mehta', 'karan.mehta@orbitly.io', 'Account Executive',
        (SELECT department_id FROM departments WHERE name = 'Sales'),
        (SELECT employee_id FROM employees WHERE email = 'isabella.rossi@orbitly.io'),
        112000, '2020-01-13', 'active', 'karan.mehta@orbitly.io'),
    ('Chloe', 'Bennett', 'chloe.bennett@orbitly.io', 'Account Executive',
        (SELECT department_id FROM departments WHERE name = 'Sales'),
        (SELECT employee_id FROM employees WHERE email = 'isabella.rossi@orbitly.io'),
        110000, '2021-06-07', 'active', 'chloe.bennett@orbitly.io'),
    ('Yusuf', 'Demir', 'yusuf.demir@orbitly.io', 'Sales Development Rep',
        (SELECT department_id FROM departments WHERE name = 'Sales'),
        (SELECT employee_id FROM employees WHERE email = 'isabella.rossi@orbitly.io'),
        78000, '2023-03-27', 'active', 'yusuf.demir@orbitly.io'),
    ('Mei', 'Lin', 'mei.lin@orbitly.io', 'Sales Development Rep',
        (SELECT department_id FROM departments WHERE name = 'Sales'),
        (SELECT employee_id FROM employees WHERE email = 'isabella.rossi@orbitly.io'),
        78000, '2023-10-16', 'remote', 'mei.lin@orbitly.io'),
    ('Jonas', 'Weber', 'jonas.weber@orbitly.io', 'Recruiter',
        (SELECT department_id FROM departments WHERE name = 'People Ops'),
        (SELECT employee_id FROM employees WHERE email = 'olivia.martins@orbitly.io'),
        92000, '2021-08-23', 'active', 'jonas.weber@orbitly.io'),
    ('Ana Cristina', 'Silva', 'ana.silva@orbitly.io', 'HR Business Partner',
        (SELECT department_id FROM departments WHERE name = 'People Ops'),
        (SELECT employee_id FROM employees WHERE email = 'olivia.martins@orbitly.io'),
        98000, '2022-07-11', 'active', 'ana.silva@orbitly.io'),
    ('Ravi', 'Chandran', 'ravi.chandran@orbitly.io', 'Financial Analyst',
        (SELECT department_id FROM departments WHERE name = 'Finance'),
        (SELECT employee_id FROM employees WHERE email = 'benjamin.cohen@orbitly.io'),
        105000, '2020-12-04', 'active', 'ravi.chandran@orbitly.io'),
    ('Sofia', 'Kowalski', 'sofia.kowalski@orbitly.io', 'Accountant',
        (SELECT department_id FROM departments WHERE name = 'Finance'),
        (SELECT employee_id FROM employees WHERE email = 'benjamin.cohen@orbitly.io'),
        96000, '2021-05-16', 'active', 'sofia.kowalski@orbitly.io'),
    ('Daniel', 'Osei', 'daniel.osei@orbitly.io', 'Payroll Specialist',
        (SELECT department_id FROM departments WHERE name = 'Finance'),
        (SELECT employee_id FROM employees WHERE email = 'benjamin.cohen@orbitly.io'),
        89000, '2022-10-30', 'on_leave', 'daniel.osei@orbitly.io');
